# Generated by Django 5.0.6 on 2024-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SAVED', 'Saved')], default='LIKE', max_length=10),
        ),
    ]
