# Generated by Django 5.0.6 on 2024-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_like_is_read_comment_saved_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
