# Generated by Django 5.0.6 on 2024-07-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.todo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.todo'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='backend.todo'),
        ),
    ]
