# Generated by Django 5.0.6 on 2024-07-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_comment_todo_alter_like_todo_alter_saved_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedTodos',
        ),
    ]
